# Generated by Django 4.0.1 on 2022-05-21 19:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_name', models.CharField(default='', max_length=500, primary_key=True, serialize=False, unique=True, verbose_name='Dataset Name')),
                ('label_1_name', models.CharField(default='', max_length=500, verbose_name='Label 1 Name')),
                ('label_2_name', models.CharField(default='', max_length=500, verbose_name='Label 2 Name')),
                ('label_3_name', models.CharField(default='', max_length=500, verbose_name='Label 3 Name')),
                ('label_4_name', models.CharField(default='', max_length=500, verbose_name='Label 4 Name')),
                ('total_accuracy', models.FloatField(default=0, verbose_name='Total Accuracy')),
                ('label1_accuracy', models.FloatField(default=0, verbose_name='Label 1 Accuracy')),
                ('label2_accuracy', models.FloatField(default=0, verbose_name='Label 2 Accuracy')),
                ('label3_accuracy', models.FloatField(default=0, verbose_name='Label 3 Accuracy')),
                ('label4_accuracy', models.FloatField(default=0, verbose_name='Label 4 Accuracy')),
                ('token_size', models.IntegerField(default=0, verbose_name='Token Size Length')),
                ('initial_trained', models.BooleanField(default=False, verbose_name='Intially Trained')),
                ('initial_train_docs', models.IntegerField(default=0, verbose_name='Initial Training Document Count')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created date Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update date Time')),
                ('dataset_name', models.CharField(default='null', max_length=500, verbose_name='Dataset Name')),
                ('document_name', models.CharField(max_length=500, verbose_name='Document Name')),
                ('document_type', models.CharField(choices=[('pdf', 'pdf'), ('text', 'text'), ('pict', 'pict')], default=0, max_length=20, verbose_name='Document Type')),
                ('document_text', models.TextField(blank=True, null=True, verbose_name='Document Text')),
                ('document_token', models.TextField(blank=True, null=True, verbose_name='Document Token')),
                ('document_size', models.FloatField(blank=True, null=True, verbose_name='Document Size')),
                ('document_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='../frontend-veritas/public/'), upload_to='dataset/')),
                ('uncertainity_score', models.FloatField(default=100)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='Word Count')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('class_a_predit_percentage', models.FloatField(null=True, verbose_name='class a predict')),
                ('class_b_predit_percentage', models.FloatField(null=True, verbose_name='class b predict')),
                ('class_c_predit_percentage', models.FloatField(null=True, verbose_name='class c predict')),
                ('class_d_predit_percentage', models.FloatField(null=True, verbose_name='class d predict')),
                ('predicted_label_name', models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Label 2'), ('Label 3', 'Label 3')], default='null', max_length=50, verbose_name='Predicted Label Name')),
                ('reviewed_label_name', models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Label 2'), ('Label 3', 'Label 3')], default='null', max_length=50, verbose_name='Reviewed Label Name')),
                ('used_for_training', models.CharField(choices=[('not_used', 'not_used'), ('in_queue', 'in_queue'), ('used', 'used')], default='not_used', max_length=50, verbose_name='Used For Training')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_project_location', models.CharField(max_length=1000, verbose_name='Main Project Path')),
                ('intial_epochs', models.IntegerField(default=0, verbose_name='Intial Epochs')),
                ('increment_epochs', models.IntegerField(default=0, verbose_name='Incremental Epochs')),
                ('inque_maxlen', models.IntegerField(default=0, verbose_name='Inque Maxlen')),
                ('batch_size', models.IntegerField(default=0, verbose_name='Batch Size')),
                ('curr_dataset', models.CharField(default='', max_length=500, verbose_name='Current Dataset')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
    ]
