# Generated by Django 4.0.1 on 2022-03-18 20:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created date Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update date Time')),
                ('document_name', models.CharField(max_length=500, verbose_name='Document Name')),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('Text', 'Text'), ('Picture', 'Picture')], default=0, max_length=20, verbose_name='Document Type')),
                ('document_text', models.TextField(blank=True, null=True, verbose_name='Document Text')),
                ('document_token', models.TextField(blank=True, null=True, verbose_name='Document Token')),
                ('document_size', models.FloatField(blank=True, null=True, verbose_name='Document Size')),
                ('document_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='../frontend-veritas/public/'), upload_to='dataset/')),
                ('uncertainity_score', models.FloatField(default=100)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='Word Count')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('class_a_predit_percentage', models.IntegerField(null=True, verbose_name='class a predict')),
                ('class_b_predit_percentage', models.IntegerField(null=True, verbose_name='class b predict')),
                ('class_c_predit_percentage', models.IntegerField(null=True, verbose_name='class c predict')),
                ('class_d_predit_percentage', models.IntegerField(null=True, verbose_name='class d predict')),
                ('predicted_label_name', models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Lable 2'), ('Label 3', 'Lable 3')], default=0, max_length=50, verbose_name='Predicted Label Name')),
                ('reviewed_label_name', models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Lable 2'), ('Label 3', 'Lable 3')], default=0, max_length=50, verbose_name='Reviewed Label Name')),
                ('used_for_training', models.CharField(choices=[('not used yet', 'not used yet'), ('in queue', 'in queue'), ('used for training', 'used for training')], default=0, max_length=50, verbose_name='Used For Training')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
