# Generated by Django 4.0.1 on 2022-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='predicted_label_name',
            field=models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Lable 2'), ('Label 3', 'Lable 3')], default='null', max_length=50, verbose_name='Predicted Label Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reviewed_label_name',
            field=models.CharField(choices=[('null', 'null'), ('Label 0', 'Label 0'), ('Label 1', 'Label 1'), ('Label 2', 'Lable 2'), ('Label 3', 'Lable 3')], default='null', max_length=50, verbose_name='Reviewed Label Name'),
        ),
    ]
