# Generated by Django 4.0.1 on 2022-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_document_predicted_label_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='class_a_predit_percentage',
            field=models.FloatField(null=True, verbose_name='class a predict'),
        ),
        migrations.AlterField(
            model_name='document',
            name='class_b_predit_percentage',
            field=models.FloatField(null=True, verbose_name='class b predict'),
        ),
        migrations.AlterField(
            model_name='document',
            name='class_c_predit_percentage',
            field=models.FloatField(null=True, verbose_name='class c predict'),
        ),
        migrations.AlterField(
            model_name='document',
            name='class_d_predit_percentage',
            field=models.FloatField(null=True, verbose_name='class d predict'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('text', 'text'), ('pict', 'pict')], default=0, max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='predicted_label_name',
            field=models.CharField(choices=[('null', 'null'), ('label_0', 'label_0'), ('label_1', 'label_1'), ('label_2', 'label_2'), ('label_3', 'label_3')], default='-', max_length=50, verbose_name='Predicted Label Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reviewed_label_name',
            field=models.CharField(choices=[('null', 'null'), ('label_0', 'label_0'), ('label_1', 'label_1'), ('label_2', 'label_2'), ('label_3', 'label_3')], default='-', max_length=50, verbose_name='Reviewed Label Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='used_for_training',
            field=models.CharField(choices=[('not_used', 'not_used'), ('in_queue', 'in_queue'), ('used', 'used')], default=0, max_length=50, verbose_name='Used For Training'),
        ),
    ]
